name: GitHub Stats Card

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    name: Update README with GitHub Stats Card
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Generate GitHub Stats Card
        run: npx github-stats-card
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update GitHub Stats Card" || echo "No changes to commit"
          git push
